"""Tests for the OrcaSlicer-independent logic: parsing, profiles, discovery.

These run without OrcaSlicer installed.
"""

import json
from pathlib import Path

import pytest

from orca_mcp import gcode, profiles

SAMPLE_GCODE = """\
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.0
; total layer number: 3
; total filament used [g] = 34.56
; total filament length [mm] : 11504.32
; estimated printing time (normal mode) = 1h 23m 45s
; HEADER_BLOCK_END
M106 S102
;LAYER_CHANGE
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
; FEATURE: Outer wall
G1 X10 Y10 E0.5 F1800
G1 X20 Y10 E1.0 F3000
; FEATURE: Sparse infill
G1 X30 Y10 E1.5 F9000
;LAYER_CHANGE
; Z_HEIGHT: 0.4
; LAYER_HEIGHT: 0.2
M106 S255
; FEATURE: Outer wall
G1 X10 Y10 E2.0 F1200
;LAYER_CHANGE
; Z_HEIGHT: 0.6
; LAYER_HEIGHT: 0.2
M107
; FEATURE: Top surface
G1 X10 Y10 E2.5 F2400
; CONFIG_BLOCK_START
; filament_type = TPU
; nozzle_diameter = 0.6
; wall_loops = 3
; CONFIG_BLOCK_END
"""


@pytest.fixture()
def gcode_file(tmp_path: Path) -> Path:
    f = tmp_path / "sample.gcode"
    f.write_text(SAMPLE_GCODE)
    return f


@pytest.fixture()
def config_dir(tmp_path: Path, monkeypatch) -> Path:
    root = tmp_path / "OrcaSlicer"
    proc = root / "user" / "default" / "process"
    proc.mkdir(parents=True)
    (proc / "my-tpu-process.json").write_text(json.dumps({
        "name": "0.2mm TPU disc",
        "inherits": "0.20mm Standard @Elegoo",
        "wall_loops": "3",
        "fan_max_speed": ["80"],
    }))
    monkeypatch.setenv("ORCASLICER_CONFIG_DIR", str(root))
    return root


class TestEstimates:
    def test_time_and_filament(self, gcode_file):
        est = gcode.parse_estimates(gcode_file)
        assert est["estimated_time_seconds"] == 5025
        assert est["estimated_time_pretty"] == "1h 23m 45s"
        assert est["filament_used_g"] == 34.56
        assert est["filament_used_mm"] == 11504.32

    def test_config_values(self, gcode_file):
        est = gcode.parse_estimates(gcode_file)
        assert est["filament_type"] == "TPU"
        assert est["nozzle_diameter"] == 0.6
        assert est["total_layers"] == 3


class TestLayerAnalysis:
    def test_layer_boundaries_and_fan(self, gcode_file):
        out = gcode.analyze_layers(gcode_file)
        assert out["layer_count_returned"] == 3
        l0, l1, l2 = out["layers"]
        # Fan set before first layer carries in; M106 S102 -> 40%
        assert l0["fan_speed_pct"] == 40.0
        assert l1["fan_speed_pct"] == 100.0
        assert l2["fan_speed_pct"] == 0.0

    def test_speed_range_and_features(self, gcode_file):
        l0 = gcode.analyze_layers(gcode_file)["layers"][0]
        assert l0["min_print_speed_mms"] == 30.0   # F1800
        assert l0["max_print_speed_mms"] == 150.0  # F9000
        assert "Outer wall" in l0["features"]
        assert "Sparse infill" in l0["features"]
        assert l0["extrusion_line_count"] == 3

    def test_z_window(self, gcode_file):
        out = gcode.analyze_layers(gcode_file, z_min=0.3, z_max=0.5)
        assert out["layer_count_returned"] == 1
        assert out["layers"][0]["z"] == 0.4

    def test_max_layers_truncation(self, gcode_file):
        out = gcode.analyze_layers(gcode_file, max_layers=2)
        assert out["layer_count_returned"] == 2
        assert out["truncated"] is True


class TestProfiles:
    def test_discovery(self, config_dir):
        profs = profiles.discover_profiles("process")
        assert len(profs) == 1
        assert profs[0].name == "my-tpu-process"
        assert profs[0].inherits == "0.20mm Standard @Elegoo"

    def test_resolve_exact_and_partial(self, config_dir):
        assert profiles.resolve_profile("my-tpu-process", "process").source == "user"
        assert profiles.resolve_profile("my-tpu", "process").name == "my-tpu-process"

    def test_resolve_missing_raises(self, config_dir):
        with pytest.raises(FileNotFoundError):
            profiles.resolve_profile("does-not-exist", "process")

    def test_resolve_path(self, config_dir, tmp_path):
        f = tmp_path / "exported.json"
        f.write_text('{"name": "exported"}')
        p = profiles.resolve_profile(str(f), "filament")
        assert p.source == "explicit"

    def test_apply_overrides(self, config_dir, tmp_path):
        p = profiles.resolve_profile("my-tpu-process", "process")
        derived = profiles.apply_overrides(
            p, {"wall_loops": 4, "fan_max_speed": 30}, tmp_path / "derived"
        )
        data = json.loads(derived.read_text())
        # Scalar stays a string, list-typed key gets wrapped
        assert data["wall_loops"] == "4"
        assert data["fan_max_speed"] == ["30"]
        # Original untouched
        original = json.loads(Path(p.path).read_text())
        assert original["wall_loops"] == "3"
        # Derived name reflects overrides
        assert "wall_loops=4" in data["name"]

    def test_invalid_type_raises(self):
        with pytest.raises(ValueError):
            profiles.discover_profiles("bogus")
